---
- name: Configure target hosts
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Ensure executing from ECS
      ansible.builtin.assert:
        fail_msg: "This playbook should be executed from ECS."
        quiet: true
        that:
          - execute_from_ecs == 'true'
      vars:
        execute_from_ecs: "{{ lookup('env', 'EXECUTE_FROM_ECS') }}"
  roles:
    - role: load_vars
    - role: awscli
    - role: local_setup
