---
- name: Install server
  hosts: all
  gather_facts: false
  roles:
    - role: check_connection
    - role: apt_upgrade
    - role: common_packages
    - role: timezone
    - role: load_vars
    - role: ssh_setup
    - role: auto_shutdown

- name: Install Master server
  hosts: master
  gather_facts: false
  roles:
    - role: ansible

- name: Reboot after installation
  hosts: all
  gather_facts: false
  roles:
    - role: reboot
