---
- name: Put private key to master server
  ansible.builtin.copy:
    src: "{{ ansible_ssh_private_key_file }}"
    dest: "~/.ssh/id_rsa"
    mode: "0600"

- name: Check SSH connection from master server
  ansible.builtin.command: >-
    ssh
    -o StrictHostKeyChecking=no
    -o UserKnownHostsFile=/dev/null
    {{ ansible_user }}@{{ target_ip }}
    whoami
  changed_when: false
  with_items: "{{ groups['targets'] }}"
  vars:
    target_ip: "{{ hostvars[item]['ansible_host'] | default(item) }}"
